package com.tuoming.entity.sgs;

public class SgsIndex {
    public final static int accessType = 0;
    public final static int interface0 = 1;
    public final static int sdrType = 2;
    public final static int imsi = 3;
    public final static int imei = 4;
    public final static int msisdn = 5;
    public final static int mcc = 6;
    public final static int mnc = 7;
    public final static int startTime = 8;
    public final static int endTime = 9;
    public final static int srvstat = 10;
    public final static int cdrstat = 11;
    public final static int xdrId = 12;
    public final static int mscIp = 13;
    public final static int mscPort = 14;
    public final static int mmeIp = 15;
    public final static int mmePort = 16;
    public final static int servType = 17;
    public final static int locUpType = 18;
    public final static int callingImsi = 19;
    public final static int callingImei = 20;
    public final static int callingMsisdn = 21;
    public final static int calledImsi = 22;
    public final static int calledImei = 23;
    public final static int calledMsisdn = 24;
    public final static int tmsi = 25;
    public final static int tai = 26;
    public final static int cellId = 27;
    public final static int newLai = 28;
    public final static int oldLai = 29;
    public final static int sgsCause = 30;
    public final static int cpCause = 31;
    public final static int rpCause = 32;
    public final static int vlrName = 33;
    public final static int mmeName = 34;
    public final static int size = 35;
    public final static String splite = "\\|";
}
